import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { AppLayout } from "@/components/layout/AppLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { TypeBadge } from "@/components/ui/type-badge";
import { ComplexityBadge } from "@/components/ui/complexity-badge";
import { ConfidenceIndicator } from "@/components/ui/confidence-indicator";
import { Separator } from "@/components/ui/separator";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import {
  ArrowLeft,
  Download,
  FileJson,
  FileText,
  Clock,
  DollarSign,
  TrendingUp,
  Sparkles,
  Bot,
} from "lucide-react";

type UseCaseType = "RPA" | "Workflow" | "Rule" | "AI Agent";
type Complexity = "Low" | "Medium" | "High";

interface UseCase {
  id: string;
  name: string;
  description: string | null;
  type: UseCaseType;
  affected_activities: string[];
  pattern_type: string;
  monthly_volume: number;
  estimated_time_saved: number;
  estimated_cost_impact: number;
  complexity: Complexity;
  confidence_score: number;
  priority_score: number;
  ai_classification: string | null;
  ai_explanation: string | null;
  suggested_approach: string | null;
  status: string;
  created_at: string;
}

export default function UseCaseDetail() {
  const { id } = useParams<{ id: string }>();
  const [useCase, setUseCase] = useState<UseCase | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id) fetchUseCase(id);
  }, [id]);

  async function fetchUseCase(ucId: string) {
    try {
      const { data, error } = await supabase
        .from("automation_use_cases")
        .select("*")
        .eq("id", ucId)
        .maybeSingle();

      if (error) throw error;
      setUseCase(data as UseCase);
    } catch (error) {
      console.error("Error fetching use case:", error);
    } finally {
      setLoading(false);
    }
  }

  const exportJSON = () => {
    if (!useCase) return;
    const blob = new Blob([JSON.stringify(useCase, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${useCase.name.replace(/\s+/g, "_")}_brief.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("JSON export downloaded");
  };

  const exportPDF = () => {
    if (!useCase) return;
    // For MVP, we'll export as a formatted text file that can be converted to PDF
    const content = `
AUTOMATION USE CASE BRIEF
=========================

Name: ${useCase.name}
Type: ${useCase.type}
Complexity: ${useCase.complexity}
Confidence: ${Math.round(useCase.confidence_score * 100)}%
Priority Score: ${Number(useCase.priority_score).toFixed(0)}

DESCRIPTION
-----------
${useCase.description || "No description available"}

AFFECTED ACTIVITIES
-------------------
${useCase.affected_activities.map((a) => `• ${a}`).join("\n")}

BUSINESS IMPACT
---------------
Monthly Volume: ${useCase.monthly_volume.toLocaleString()} executions
Time Saved: ${useCase.estimated_time_saved} minutes/month
Cost Impact: $${Number(useCase.estimated_cost_impact).toLocaleString()}/month

AI ANALYSIS
-----------
Classification: ${useCase.ai_classification || "Pending"}
${useCase.ai_explanation || ""}

SUGGESTED APPROACH
------------------
${useCase.suggested_approach || "See automation type for recommended approach."}

Pattern Detected: ${useCase.pattern_type.replace(/_/g, " ")}

---
Generated by AutoFlow Discovery
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${useCase.name.replace(/\s+/g, "_")}_brief.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Brief exported (text format)");
  };

  if (loading) {
    return (
      <AppLayout>
        <div className="flex h-full items-center justify-center">
          <div className="animate-pulse text-muted-foreground">Loading...</div>
        </div>
      </AppLayout>
    );
  }

  if (!useCase) {
    return (
      <AppLayout>
        <div className="text-center">
          <h2 className="text-xl font-semibold">Use case not found</h2>
          <Button asChild className="mt-4">
            <Link to="/use-cases">Back to Catalog</Link>
          </Button>
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <div className="space-y-6 animate-fade-in">
        {/* Header */}
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="flex items-start gap-4">
            <Button variant="ghost" size="icon" asChild>
              <Link to="/use-cases">
                <ArrowLeft className="h-5 w-5" />
              </Link>
            </Button>
            <div>
              <div className="flex items-center gap-3">
                <h1 className="text-2xl font-semibold">{useCase.name}</h1>
                <TypeBadge type={useCase.type} />
                <ComplexityBadge complexity={useCase.complexity} />
              </div>
              {useCase.description && (
                <p className="mt-1 text-muted-foreground">
                  {useCase.description}
                </p>
              )}
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={exportJSON}>
              <FileJson className="mr-2 h-4 w-4" />
              Export JSON
            </Button>
            <Button variant="outline" size="sm" onClick={exportPDF}>
              <FileText className="mr-2 h-4 w-4" />
              Export Brief
            </Button>
          </div>
        </div>

        {/* Key Metrics */}
        <div className="grid gap-4 md:grid-cols-4">
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                  <TrendingUp className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="text-2xl font-semibold">
                    {useCase.monthly_volume.toLocaleString()}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    Monthly Executions
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-chart-2/10">
                  <Clock className="h-5 w-5 text-chart-2" />
                </div>
                <div>
                  <p className="text-2xl font-semibold">
                    {(useCase.estimated_time_saved / 60).toFixed(1)}h
                  </p>
                  <p className="text-sm text-muted-foreground">
                    Time Saved/Month
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-success/10">
                  <DollarSign className="h-5 w-5 text-success" />
                </div>
                <div>
                  <p className="text-2xl font-semibold text-success">
                    ${Number(useCase.estimated_cost_impact).toLocaleString()}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    Monthly Savings
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-warning/10">
                  <Sparkles className="h-5 w-5 text-warning" />
                </div>
                <div>
                  <p className="text-2xl font-semibold">
                    {Number(useCase.priority_score).toFixed(0)}
                  </p>
                  <p className="text-sm text-muted-foreground">Priority Score</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="grid gap-6 lg:grid-cols-3">
          {/* Main Details */}
          <div className="lg:col-span-2 space-y-6">
            {/* AI Analysis */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base">
                  <Bot className="h-5 w-5 text-primary" />
                  AI Analysis
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground">
                      Classification
                    </p>
                    <Badge variant="secondary" className="mt-1">
                      {useCase.ai_classification || "Pending Analysis"}
                    </Badge>
                  </div>
                  <Separator orientation="vertical" className="h-10" />
                  <div>
                    <p className="text-sm text-muted-foreground">Confidence</p>
                    <div className="mt-1">
                      <ConfidenceIndicator score={useCase.confidence_score} />
                    </div>
                  </div>
                </div>

                {useCase.ai_explanation ? (
                  <div className="rounded-lg bg-muted/50 p-4">
                    <p className="text-sm leading-relaxed">
                      {useCase.ai_explanation}
                    </p>
                  </div>
                ) : (
                  <div className="rounded-lg bg-muted/50 p-4 text-center text-muted-foreground">
                    AI analysis pending. Check back soon for detailed insights.
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Suggested Approach */}
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Suggested Approach</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <TypeBadge type={useCase.type} />
                    <div>
                      <p className="font-medium">
                        {useCase.type === "RPA" && "Robotic Process Automation"}
                        {useCase.type === "Workflow" && "Workflow Automation"}
                        {useCase.type === "Rule" && "Business Rule Engine"}
                        {useCase.type === "AI Agent" && "AI-Powered Agent"}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        {useCase.type === "RPA" &&
                          "Use RPA bots to mimic human interactions with applications. Ideal for repetitive, rule-based tasks."}
                        {useCase.type === "Workflow" &&
                          "Implement workflow automation to orchestrate tasks across systems. Best for multi-step processes."}
                        {useCase.type === "Rule" &&
                          "Deploy a rule engine to automate decision-making. Perfect for approval/validation logic."}
                        {useCase.type === "AI Agent" &&
                          "Leverage AI agents for intelligent automation. Suitable for tasks requiring judgment."}
                      </p>
                    </div>
                  </div>

                  {useCase.suggested_approach && (
                    <div className="rounded-lg border border-border bg-card p-4">
                      <p className="text-sm">{useCase.suggested_approach}</p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Affected Activities */}
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Affected Activities</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {useCase.affected_activities.map((activity, idx) => (
                    <div
                      key={idx}
                      className="flex items-center gap-2 rounded-lg bg-muted/50 px-3 py-2"
                    >
                      <div className="h-2 w-2 rounded-full bg-primary" />
                      <span className="text-sm">{activity}</span>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Pattern Info */}
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Detection Pattern</CardTitle>
              </CardHeader>
              <CardContent>
                <Badge variant="outline" className="capitalize">
                  {useCase.pattern_type.replace(/_/g, " ")}
                </Badge>
                <p className="mt-2 text-sm text-muted-foreground">
                  {useCase.pattern_type === "high_frequency_low_variance" &&
                    "This activity occurs frequently with consistent timing, making it ideal for automation."}
                  {useCase.pattern_type === "rework_loop" &&
                    "Repeated execution of the same activity indicates validation or correction opportunities."}
                  {useCase.pattern_type === "long_waiting_time" &&
                    "Significant delays before this activity suggest auto-assignment potential."}
                  {useCase.pattern_type === "always_approved" &&
                    "Approvals consistently pass, indicating rule-based automation opportunity."}
                  {useCase.pattern_type === "data_transfer" &&
                    "Manual data movement between systems can be automated."}
                </p>
              </CardContent>
            </Card>

            {/* Status */}
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Status</CardTitle>
              </CardHeader>
              <CardContent>
                <Badge
                  variant={useCase.status === "new" ? "secondary" : "default"}
                  className="capitalize"
                >
                  {useCase.status}
                </Badge>
                <p className="mt-2 text-xs text-muted-foreground">
                  Created{" "}
                  {new Date(useCase.created_at).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                  })}
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
